package com.healthgame.backend.support;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.charset.StandardCharsets;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
public abstract class IntegrationTestSupport {
    private static final String TEST_DB = "it_" + UUID.randomUUID().toString().replace("-", "");

    @Autowired
    protected MockMvc mockMvc;

    @Autowired
    protected ObjectMapper objectMapper;

    @Autowired
    protected JdbcTemplate jdbcTemplate;

    @DynamicPropertySource
    static void registerProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", () -> "jdbc:h2:mem:" + TEST_DB + ";MODE=PostgreSQL;NON_KEYWORDS=VALUE;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH");
        registry.add("spring.datasource.driver-class-name", () -> "org.h2.Driver");
        registry.add("spring.datasource.username", () -> "sa");
        registry.add("spring.datasource.password", () -> "");
        registry.add("spring.data.redis.host", () -> "localhost");
        registry.add("spring.data.redis.port", () -> "6379");
        registry.add("spring.flyway.enabled", () -> "false");
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "create-drop");
    }

    @BeforeEach
    void prepareJdbcOnlyTables() {
        jdbcTemplate.execute("""
                create table if not exists roles (
                    id smallint generated by default as identity primary key,
                    code varchar(32) not null unique,
                    description varchar(255)
                )
                """);
        jdbcTemplate.execute("""
                create table if not exists user_roles (
                    user_id bigint not null,
                    role_id smallint not null,
                    primary key (user_id, role_id)
                )
                """);
        jdbcTemplate.execute("""
                merge into roles (code, description)
                key(code)
                values
                    ('ROLE_USER', 'Default user role'),
                    ('ROLE_ADMIN', 'Administrative role')
                """);
        jdbcTemplate.execute("""
                merge into achievements (code, name, description, icon, rarity, is_active)
                key(code)
                values
                    ('FIRST_CHECKIN', 'First Check-in', 'Awarded for the first completed habit check-in', 'sparkles', 'common', true),
                    ('CHALLENGE_JOINER', 'Challenge Joiner', 'Awarded for joining the first challenge', 'flag', 'common', true)
                """);
    }

    protected AuthTokens registerAndLogin() throws Exception {
        String suffix = UUID.randomUUID().toString().replace("-", "").substring(0, 8);
        String numericSuffix = String.valueOf(Math.abs(suffix.hashCode()));
        String email = "tester_" + suffix + "@example.com";
        String password = "Password123";
        String nickname = "tester_" + suffix;

        mockMvc.perform(post("/api/v1/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "email": "%s",
                                  "phone": "+37529%s",
                                  "password": "%s",
                                  "nickname": "%s",
                                  "firstName": "Test",
                                  "timezone": "Europe/Minsk"
                                }
                                """.formatted(email, numericSuffix.substring(0, Math.min(9, numericSuffix.length())), password, nickname)))
                .andExpect(status().isCreated());

        MvcResult loginResult = mockMvc.perform(post("/api/v1/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "login": "%s",
                                  "password": "%s"
                                }
                                """.formatted(email, password)))
                .andExpect(status().isOk())
                .andReturn();

        JsonNode payload = readBody(loginResult);
        return new AuthTokens(
                email,
                password,
                payload.path("accessToken").asText(),
                payload.path("refreshToken").asText()
        );
    }

    protected JsonNode readBody(MvcResult result) throws Exception {
        return objectMapper.readTree(result.getResponse().getContentAsString(StandardCharsets.UTF_8));
    }

    protected record AuthTokens(
            String email,
            String password,
            String accessToken,
            String refreshToken
    ) {
    }
}
